import { BadRequestException } from "@nestjs/common";
import { describe, expect, it, vi } from "vitest";
import { ResourceNotFoundError } from "@/application/errors/application.error";
import {
  createMockAgendamentoRepository,
  createMockColecaoSyncService,
  createMockPermissionChecker,
  createTestAccessContext,
  createTestId,
} from "@/test/helpers";
import { CalendarioAgendamento } from "../../domain/calendario-agendamento";
import { CalendarioAgendamentoTipo } from "../../domain/calendario-agendamento.types";
import { CalendarioAgendamentoConflitoService } from "../calendario-agendamento-conflito.service";
import { CalendarioAgendamentoAdicionarDataAvulsaCommandHandlerImpl } from "./calendario-agendamento-adicionar-data-avulsa.command.handler";

function createConflitoService(repository: object) {
  return new CalendarioAgendamentoConflitoService(
    repository as never,
    { execute: vi.fn().mockResolvedValue(null) } as never,
    { execute: vi.fn().mockResolvedValue([]) } as never,
  );
}

function criarSerieRecorrente(overrides: Record<string, unknown> = {}) {
  return CalendarioAgendamento.create({
    tipo: CalendarioAgendamentoTipo.AULA,
    dataInicio: "2026-03-03", // terça-feira
    diaInteiro: false,
    horarioInicio: "08:00:00",
    horarioFim: "09:00:00",
    repeticao: "FREQ=WEEKLY;BYDAY=TU;COUNT=10",
    turmas: [{ id: createTestId() }],
    ...overrides,
  });
}

describe("CalendarioAgendamentoAdicionarDataAvulsaCommandHandler", () => {
  function createHandler(
    overrides: {
      repository?: object;
      permissionChecker?: object;
      colecaoSyncService?: object;
    } = {},
  ) {
    const repository = overrides.repository ?? createMockAgendamentoRepository();
    const permissionChecker = overrides.permissionChecker ?? createMockPermissionChecker();
    const colecaoSyncService = overrides.colecaoSyncService ?? createMockColecaoSyncService();

    const handler = new CalendarioAgendamentoAdicionarDataAvulsaCommandHandlerImpl(
      repository as any,
      permissionChecker as any,
      colecaoSyncService as any,
      createConflitoService(repository) as any,
    );

    return { handler, repository, permissionChecker, colecaoSyncService };
  }

  it("should create an addition referencing the origin series with dataOcorrenciaReferenciada null", async () => {
    const serie = criarSerieRecorrente();

    const repository = createMockAgendamentoRepository();
    repository.loadById.mockResolvedValue(serie);
    repository.getFindOneQueryResult.mockResolvedValue({ id: "avulsa-id" });

    const { handler } = createHandler({ repository });

    // sábado — a regra é toda terça, então essa data não é gerada pela RRULE
    const result = await handler.execute(createTestAccessContext(), {
      id: serie.id,
      dataOcorrencia: "2026-03-14",
      horarioInicio: "10:00:00",
    });

    expect(result).toEqual({ id: "avulsa-id" });
    expect(repository.save).toHaveBeenCalledOnce();

    const salvo = repository.save.mock.calls[0][0] as CalendarioAgendamento;
    expect(salvo.identificadorExternoSerieOrigem).toBe(serie.identificadorExterno);
    expect(salvo.dataOcorrenciaReferenciada).toBeNull();
    expect(salvo.dataInicio).toBe("2026-03-14");
    expect(salvo.horarioInicio).toBe("10:00:00");
    expect(salvo.repeticao).toBeNull();
  });

  it("should throw when the target agendamento is not recurring", async () => {
    const serie = CalendarioAgendamento.create({
      tipo: CalendarioAgendamentoTipo.EVENTO,
      dataInicio: "2026-03-02",
      diaInteiro: true,
    });

    const repository = createMockAgendamentoRepository();
    repository.loadById.mockResolvedValue(serie);

    const { handler } = createHandler({ repository });

    await expect(
      handler.execute(createTestAccessContext(), {
        id: serie.id,
        dataOcorrencia: "2026-03-14",
      }),
    ).rejects.toThrow(BadRequestException);
  });

  it("should reject a date already generated by the RRULE", async () => {
    const serie = criarSerieRecorrente();

    const repository = createMockAgendamentoRepository();
    repository.loadById.mockResolvedValue(serie);

    const { handler } = createHandler({ repository });

    // 2026-03-10 é uma terça-feira dentro do alcance da regra semanal
    await expect(
      handler.execute(createTestAccessContext(), {
        id: serie.id,
        dataOcorrencia: "2026-03-10",
      }),
    ).rejects.toThrow(BadRequestException);

    expect(repository.save).not.toHaveBeenCalled();
  });

  it("should exclude the origin series from the conflict check", async () => {
    const serie = criarSerieRecorrente();

    const repository = createMockAgendamentoRepository();
    repository.loadById.mockResolvedValue(serie);
    repository.getFindOneQueryResult.mockResolvedValue({ id: "avulsa-id" });

    const { handler } = createHandler({ repository });

    await handler.execute(createTestAccessContext(), {
      id: serie.id,
      dataOcorrencia: "2026-03-14",
    });

    expect(repository.findConflicting).toHaveBeenCalledWith(
      expect.objectContaining({ excludeIdentificadorExterno: serie.identificadorExterno }),
    );
  });

  it("should throw BadRequestException when findConflicting returns conflicts", async () => {
    const serie = criarSerieRecorrente();

    const repository = createMockAgendamentoRepository();
    repository.loadById.mockResolvedValue(serie);
    repository.findConflicting.mockResolvedValue([
      { id: createTestId(), identificadorExterno: "ext-1", recurso: "turma", recursoId: "t-1" },
    ]);

    const { handler } = createHandler({ repository });

    await expect(
      handler.execute(createTestAccessContext(), {
        id: serie.id,
        dataOcorrencia: "2026-03-14",
      }),
    ).rejects.toThrow(BadRequestException);
  });

  it("should throw when the origin series does not exist", async () => {
    const repository = createMockAgendamentoRepository();
    repository.loadById.mockResolvedValue(null);

    const { handler } = createHandler({ repository });

    await expect(
      handler.execute(createTestAccessContext(), {
        id: createTestId(),
        dataOcorrencia: "2026-03-14",
      }),
    ).rejects.toThrow();
  });

  it("should throw ResourceNotFoundError when getFindOneQueryResult returns null after save", async () => {
    const serie = criarSerieRecorrente();

    const repository = createMockAgendamentoRepository();
    repository.loadById.mockResolvedValue(serie);
    repository.getFindOneQueryResult.mockResolvedValue(null);

    const { handler } = createHandler({ repository });

    await expect(
      handler.execute(createTestAccessContext(), {
        id: serie.id,
        dataOcorrencia: "2026-03-14",
      }),
    ).rejects.toThrow(ResourceNotFoundError);
  });

  describe("colecao sync hook", () => {
    it("should register a sync change when the addition has a colecao", async () => {
      const colecaoId = createTestId();
      const serie = criarSerieRecorrente({ colecao: { id: colecaoId } });

      const repository = createMockAgendamentoRepository();
      repository.loadById.mockResolvedValue(serie);
      repository.getFindOneQueryResult.mockResolvedValue({ id: "avulsa-id" });

      const colecaoSyncService = createMockColecaoSyncService();
      const { handler } = createHandler({ repository, colecaoSyncService });

      await handler.execute(createTestAccessContext(), {
        id: serie.id,
        dataOcorrencia: "2026-03-14",
      });

      expect(colecaoSyncService.registrarMudanca).toHaveBeenCalledWith({
        colecaoId,
        agendamentoId: expect.any(String),
        tipoOperacao: "adicionar-data-avulsa",
      });
    });

    it("should not register a sync change when the addition has no colecao", async () => {
      const serie = criarSerieRecorrente();

      const repository = createMockAgendamentoRepository();
      repository.loadById.mockResolvedValue(serie);
      repository.getFindOneQueryResult.mockResolvedValue({ id: "avulsa-id" });

      const colecaoSyncService = createMockColecaoSyncService();
      const { handler } = createHandler({ repository, colecaoSyncService });

      await handler.execute(createTestAccessContext(), {
        id: serie.id,
        dataOcorrencia: "2026-03-14",
      });

      expect(colecaoSyncService.registrarMudanca).not.toHaveBeenCalled();
    });
  });
});
