x-podman:
  in_pod: false

services:
  ladesa-management-service:
    container_name: ladesa-management-service
    hostname: ladesa-management-service
    user: root
    build:
      context: .
      target: devcontainer
    command:
      - sleep
      - infinity
    depends_on:
      - ladesa-management-service-db
    networks:
      - ladesa-net
    ports:
      - "3701:3701"
      - "9229:9229"
    working_dir: /ladesa/management-service
    userns_mode: keep-id:uid=1000,gid=1000
    volumes:
      - .:/ladesa/management-service:z
      - ladesa-management-service-uploaded-files:/container/uploaded
      - ./volumes/history/root-zsh:/root/.zsh_history:z
      - ./volumes/history/root-bash:/root/.bash_history:z
      - ./volumes/history/happy-zsh:/home/happy/.zsh_history:z
      - ./volumes/history/happy-bash:/home/happy/.bash_history:z
    environment:
      - STORAGE_PATH=/container/uploaded
    env_file:
      - .env

  ladesa-management-service-db:
    image: docker.io/bitnami/postgresql:15
    container_name: ladesa-management-service-db
    volumes:
      - "ladesa-management-service-db-data:/bitnami/postgresql"
      # - './volumes/db/scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    networks:
      - ladesa-net
    ports:
      - "5432:5432"
    env_file:
      - .db.env

networks:
  ladesa-net:
    external: true

volumes:
  ladesa-management-service-db-data:
  ladesa-management-service-uploaded-files:
