**/.git
**/.husky
**/.github

**/.vscode
**/.idea

**/.pnpm-store
**/node_modules

**/*.env
**/*.env*

**/.nx
**/volumes

Dockerfile
*.dockerignore

packages/*/test
packages/*/dist
packages/*/.dist

Makefile