services:
  ladesa-api:
    build:
      context: .
      target: base
    user: root
    command: sh -c "sleep infinity"
    container_name: ladesa-api
    # working_dir: /var/lib/ladesa/.sources/apiapi-service/
    working_dir: /var/lib/ladesa/.sources/api
    depends_on:
      - ladesa-api-db
    networks:
      - ladesa-net
    ports:
      - 3701:3701
      - 9229:9229
    volumes:
      - ./:/var/lib/ladesa/.sources/api
      - ./api-service/volumes/uploaded:/container/uploaded
    environment:
      - STORAGE_PATH=/container/uploaded
    env_file:
      - .env

  ladesa-api-db:
    image: bitnami/postgresql:15
    container_name: ladesa-api-db
    volumes:
      - "ladesa-api-db-data:/bitnami/postgresql"
      # - './volumes/db/scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    networks:
      - ladesa-net
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - .db.env

networks:
  ladesa-net:
    external: true

volumes:
  ladesa-api-db-data:
  ladesa-api-uploaded-files:
