forceLegacyDeploy: true

packages:
  - './'
  - './services/api'
  - './services/api/src/domain/contracts'
  - './services/docs/*'
  - './packages/integrations/npm/*'
  - './packages/integrations/openapi-json'
