import { v7 as uuidv7 } from "uuid";

// Tipos para tipagem dos seeds
interface SeedEntity {
  id: string;
  dateCreated: string;
  dateUpdated: string;
  dateDeleted: null;
}

const now = new Date().toISOString();

// ============================================
// CIDADES (LOCALIDADES)
// ============================================
export const cidades = [
  {
    id: uuidv7(),
    nome: "Ji-Paraná",
    estado: "RO",
    pais: "Brasil",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Cacoal",
    estado: "RO",
    pais: "Brasil",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Porto Velho",
    estado: "RO",
    pais: "Brasil",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Ouro Preto",
    estado: "RO",
    pais: "Brasil",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// ENDEREÇOS
// ============================================
export const enderecos = [
  {
    id: uuidv7(),
    cep: "76900000",
    logradouro: "Rua Rio Amazonas",
    numero: 151,
    bairro: "Jardim dos Migrantes",
    complemento: "Bloco A",
    pontoReferencia: "Próximo ao parque",
    idCidadeFk: cidades[0].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    cep: "78950000",
    logradouro: "Manoel Vitor Diniz",
    numero: 2380,
    bairro: "Jardim São Pedro",
    complemento: null,
    pontoReferencia: "Centro",
    idCidadeFk: cidades[1].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    cep: "76800000",
    logradouro: "Avenida São Paulo",
    numero: 500,
    bairro: "Centro",
    complemento: "Sala 200",
    pontoReferencia: "Próximo à prefeitura",
    idCidadeFk: cidades[2].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    cep: "78860000",
    logradouro: "Avenida Aracaju",
    numero: 1072,
    bairro: "Riachuelo",
    complemento: null,
    pontoReferencia: null,
    idCidadeFk: cidades[3].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// CAMPUS
// ============================================
export const campus = [
  {
    id: uuidv7(),
    nomeFantasia: "IFRO - Campus Ji-Paraná",
    razaoSocial: "Instituto Federal de Educação, Ciências e Tecnologia de Rondônia",
    apelido: "ifro-jp",
    cnpj: "10817343000288",
    idEnderecoFk: enderecos[0].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nomeFantasia: "IFRO - Campus Cacoal",
    razaoSocial: "Instituto Federal de Educação, Ciências e Tecnologia de Rondônia",
    apelido: "ifro-cacoal",
    cnpj: "10817343000289",
    idEnderecoFk: enderecos[1].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nomeFantasia: "Universidade Federal de Rondônia",
    razaoSocial: "Universidade Federal de Rondônia - UNIR",
    apelido: "unir",
    cnpj: "04418943000190",
    idEnderecoFk: enderecos[2].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// MODALIDADES
// ============================================
export const modalidades = [
  {
    id: uuidv7(),
    nome: "Técnico Integrado",
    slug: "tecnico-integrado",
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Técnico Subsequente",
    slug: "tecnico-subsequente",
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Bacharelado",
    slug: "bacharelado",
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Licenciatura",
    slug: "licenciatura",
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// NÍVEIS DE FORMAÇÃO
// ============================================
export const niveisFormacao = [
  {
    id: uuidv7(),
    nome: "Nível Médio",
    slug: "nivel-medio",
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Graduação",
    slug: "graduacao",
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Pós-Graduação",
    slug: "pos-graduacao",
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// OFERTAS DE FORMAÇÃO
// ============================================
export const ofertasFormacao = [
  {
    id: uuidv7(),
    nome: "Técnico em Informática Integrado ao Ensino Médio",
    apelido: "tecnico-info-integrado",
    duracaoPeriodoEmMeses: 36,
    idModalidadeFk: modalidades[0].id,
    idCampusFk: campus[0].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Técnico em Química Integrado ao Ensino Médio",
    apelido: "tecnico-quimica-integrado",
    duracaoPeriodoEmMeses: 36,
    idModalidadeFk: modalidades[0].id,
    idCampusFk: campus[0].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Técnico em Florestas Integrado ao Ensino Médio",
    apelido: "tecnico-florestas-integrado",
    duracaoPeriodoEmMeses: 36,
    idModalidadeFk: modalidades[0].id,
    idCampusFk: campus[0].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Bacharelado em Engenharia Florestal",
    apelido: "bach-eng-florestal",
    duracaoPeriodoEmMeses: 48,
    idModalidadeFk: modalidades[2].id,
    idCampusFk: campus[0].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Licenciatura em Química",
    apelido: "lic-quimica",
    duracaoPeriodoEmMeses: 48,
    idModalidadeFk: modalidades[3].id,
    idCampusFk: campus[0].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// CURSOS
// ============================================
export const cursos = [
  {
    id: uuidv7(),
    nome: "Técnico em Informática Integrado ao Ensino Médio",
    nomeAbreviado: "TEC-INFO",
    quantidadePeriodos: 6,
    idCampusFk: campus[0].id,
    idOfertaFormacaoFk: ofertasFormacao[0].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Técnico em Química Integrado ao Ensino Médio",
    nomeAbreviado: "TEC-QUIM",
    quantidadePeriodos: 6,
    idCampusFk: campus[0].id,
    idOfertaFormacaoFk: ofertasFormacao[1].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Técnico em Florestas Integrado ao Ensino Médio",
    nomeAbreviado: "TEC-FLORES",
    quantidadePeriodos: 6,
    idCampusFk: campus[0].id,
    idOfertaFormacaoFk: ofertasFormacao[2].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Bacharelado em Engenharia Florestal",
    nomeAbreviado: "ENG-FLOR",
    quantidadePeriodos: 8,
    idCampusFk: campus[0].id,
    idOfertaFormacaoFk: ofertasFormacao[3].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Licenciatura em Química",
    nomeAbreviado: "LIC-QUIM",
    quantidadePeriodos: 8,
    idCampusFk: campus[0].id,
    idOfertaFormacaoFk: ofertasFormacao[4].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// TURMAS
// ============================================
export const turmas = [
  {
    id: uuidv7(),
    periodo: "2024.1",
    nome: "Turma A - 1º Período",
    idAmbientePadraoAulaFk: null,
    idCursoFk: cursos[0].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    periodo: "2024.1",
    nome: "Turma B - 2º Período",
    idAmbientePadraoAulaFk: null,
    idCursoFk: cursos[0].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    periodo: "2024.1",
    nome: "Turma A - 1º Período",
    idAmbientePadraoAulaFk: null,
    idCursoFk: cursos[1].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    periodo: "2024.1",
    nome: "Turma A - 1º Período",
    idAmbientePadraoAulaFk: null,
    idCursoFk: cursos[3].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    periodo: "2024.1",
    nome: "Turma A - 1º Período",
    idAmbientePadraoAulaFk: null,
    idCursoFk: cursos[4].id,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// CARGOS
// ============================================
export const cargos = [
  {
    id: uuidv7(),
    nome: "Diretor",
    descricao: "Diretor da instituição",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Coordenador de Estágio",
    descricao: "Responsável pela coordenação de estágios",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Professor",
    descricao: "Docente da instituição",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Orientador de Estágio",
    descricao: "Orientador responsável pelo acompanhamento de estágios",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Coordenador de Curso",
    descricao: "Coordenador responsável pelo curso",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// USUÁRIOS
// ============================================
export const usuarios = [
  {
    id: uuidv7(),
    nome: "Jefferson Antônio dos Santos",
    matricula: "2995931",
    email: "jefferson.santos@ifro.edu.br",
    isSuperUser: false,
    idImagemCapaFk: null,
    idImagemPerfilFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Walter Ferreira Siqueira",
    matricula: "1681121",
    email: "walter.ferreira@ifro.edu.br",
    isSuperUser: false,
    idImagemCapaFk: null,
    idImagemPerfilFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Clayton Ferraz Andrade",
    matricula: "1986393",
    email: "clayton.andrade@ifro.edu.br",
    isSuperUser: false,
    idImagemCapaFk: null,
    idImagemPerfilFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Emi Silva de Oliveira",
    matricula: "2291377",
    email: "emi.oliveira@ifro.edu.br",
    isSuperUser: false,
    idImagemCapaFk: null,
    idImagemPerfilFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Rafael Vieira",
    matricula: "1408812",
    email: "rafael.vieira@ifro.edu.br",
    isSuperUser: false,
    idImagemCapaFk: null,
    idImagemPerfilFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Leiva Custodio Pereira",
    matricula: "1938406",
    email: "leiva.pereira@ifro.edu.br",
    isSuperUser: false,
    idImagemCapaFk: null,
    idImagemPerfilFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Hailton Cesar Alves dos Reis",
    matricula: "1576313",
    email: "hailton.reis@ifro.edu.br",
    isSuperUser: false,
    idImagemCapaFk: null,
    idImagemPerfilFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Danilo Pereira Escudero",
    matricula: "1074986",
    email: "danilo.escudero@ifro.edu.br",
    isSuperUser: false,
    idImagemCapaFk: null,
    idImagemPerfilFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Pamela Siqueira Oliveira de Jesus",
    matricula: "1238077",
    email: "pamela.siqueira@ifro.edu.br",
    isSuperUser: false,
    idImagemCapaFk: null,
    idImagemPerfilFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Jairo da Rocha Pires",
    matricula: "3480064",
    email: "jairo.rocha@ifro.edu.br",
    isSuperUser: false,
    idImagemCapaFk: null,
    idImagemPerfilFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Rafaely Pantoja Oliveira",
    matricula: "3516158",
    email: "rafaely.oliveira@ifro.edu.br",
    isSuperUser: false,
    idImagemCapaFk: null,
    idImagemPerfilFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Elza Paula Silva Rocha",
    matricula: "2954427",
    email: "elza.rocha@ifro.edu.br",
    isSuperUser: false,
    idImagemCapaFk: null,
    idImagemPerfilFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// PERFIS (VÍNCULOS)
// ============================================
export const perfis = [
  {
    id: uuidv7(),
    ativo: true,
    idCargoFk: cargos[2].id, // Professor
    idCampusFk: campus[0].id,
    idUsuarioFk: usuarios[0].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    ativo: true,
    idCargoFk: cargos[2].id, // Professor
    idCampusFk: campus[0].id,
    idUsuarioFk: usuarios[1].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    ativo: true,
    idCargoFk: cargos[2].id, // Professor
    idCampusFk: campus[0].id,
    idUsuarioFk: usuarios[2].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    ativo: true,
    idCargoFk: cargos[3].id, // Orientador
    idCampusFk: campus[0].id,
    idUsuarioFk: usuarios[3].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    ativo: true,
    idCargoFk: cargos[3].id, // Orientador
    idCampusFk: campus[0].id,
    idUsuarioFk: usuarios[4].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    ativo: true,
    idCargoFk: cargos[3].id, // Orientador
    idCampusFk: campus[0].id,
    idUsuarioFk: usuarios[5].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    ativo: true,
    idCargoFk: cargos[3].id, // Orientador
    idCampusFk: campus[0].id,
    idUsuarioFk: usuarios[6].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// ESTAGIÁRIOS
// ============================================
export const estagiarios = [
  {
    id: uuidv7(),
    idPerfilFk: perfis[0].id,
    idCursoFk: cursos[0].id,
    idTurmaFk: turmas[0].id,
    telefone: "(69) 99301-3785",
    emailInstitucional: "arthur.rodrigues@estudante.ifro.edu.br",
    dataNascimento: "2006-05-15",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    idPerfilFk: perfis[1].id,
    idCursoFk: cursos[0].id,
    idTurmaFk: turmas[0].id,
    telefone: "(69) 99235-3853",
    emailInstitucional: "krauser.m@estudante.ifro.edu.br",
    dataNascimento: "2006-08-22",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    idPerfilFk: perfis[2].id,
    idCursoFk: cursos[1].id,
    idTurmaFk: turmas[2].id,
    telefone: "(69) 99264-6420",
    emailInstitucional: "andressa.maltezo@estudante.ifro.edu.br",
    dataNascimento: "2007-01-10",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    idPerfilFk: perfis[3].id,
    idCursoFk: cursos[3].id,
    idTurmaFk: turmas[3].id,
    telefone: "(69) 9 9317-7667",
    emailInstitucional: "miriam.trindade@estudante.ifro.edu.br",
    dataNascimento: "2000-03-12",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    idPerfilFk: perfis[4].id,
    idCursoFk: cursos[4].id,
    idTurmaFk: turmas[4].id,
    telefone: "(69) 99323-7730",
    emailInstitucional: "b.angela@estudante.ifro.edu.br",
    dataNascimento: "2005-07-18",
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// EMPRESAS
// ============================================
export const empresas = [
  {
    id: uuidv7(),
    razaoSocial: "Instituto Federal de Educação, Ciências e Tecnologia de Rondônia",
    nomeFantasia: "IFRO",
    cnpj: "10817343000288",
    telefone: "(69) 98484-5323",
    email: "contato@ifro.edu.br",
    idEnderecoFk: enderecos[0].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    razaoSocial: "Universidade Federal de Rondônia",
    nomeFantasia: "UNIR",
    cnpj: "04418943000190",
    telefone: "(69) 98484-5323",
    email: "contato@unir.br",
    idEnderecoFk: enderecos[2].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    razaoSocial: "ADL Informática Ltda",
    nomeFantasia: "ADL",
    cnpj: "11994158000140",
    telefone: "(69) 99301-3785",
    email: "contato@adl.com.br",
    idEnderecoFk: enderecos[0].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    razaoSocial: "Afya Centro Universitário de Ji-Paraná",
    nomeFantasia: "AFYA",
    cnpj: "84596170001142",
    telefone: "(69) 99235-3853",
    email: "contato@afya.com.br",
    idEnderecoFk: enderecos[0].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    razaoSocial: "Naturalis Farmácia de Manipulação Ltda",
    nomeFantasia: "Naturalis",
    cnpj: "21130401000217",
    telefone: "(69) 99245-2572",
    email: "contato@naturalis.com.br",
    idEnderecoFk: enderecos[3].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// ESTÁGIOS
// ============================================
export const estagios = [
  {
    id: uuidv7(),
    idEmpresaFk: empresas[0].id,
    idEstagiarioFk: estagiarios[0].id,
    idUsuarioOrientadorFk: usuarios[3].id,
    cargaHoraria: 400,
    dataInicio: "2024-04-20",
    dataFim: "2024-06-22",
    status: "EM_FASE_INICIAL",
    nomeSupervisor: "Jefferson Antônio dos Santos",
    emailSupervisor: "jefferson.santos@ifro.edu.br",
    telefoneSupervisor: "69 9 9226-0959",
    aditivo: false,
    tipoAditivo: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    idEmpresaFk: empresas[0].id,
    idEstagiarioFk: estagiarios[1].id,
    idUsuarioOrientadorFk: usuarios[0].id,
    cargaHoraria: 400,
    dataInicio: "2024-04-20",
    dataFim: "2024-06-22",
    status: "EM_FASE_INICIAL",
    nomeSupervisor: "Jefferson Antônio dos Santos",
    emailSupervisor: "jefferson.santos@ifro.edu.br",
    telefoneSupervisor: "69 9 9226-0959",
    aditivo: false,
    tipoAditivo: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    idEmpresaFk: empresas[4].id,
    idEstagiarioFk: estagiarios[2].id,
    idUsuarioOrientadorFk: usuarios[8].id,
    cargaHoraria: 400,
    dataInicio: "2024-02-16",
    dataFim: "2024-04-17",
    status: "COM_PENDENCIA",
    nomeSupervisor: "Ramila Silva de Jesus Estevam",
    emailSupervisor: "ramila-sjestevam@outlook.com",
    telefoneSupervisor: "69 99245-2572",
    aditivo: false,
    tipoAditivo: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    idEmpresaFk: empresas[1].id,
    idEstagiarioFk: estagiarios[3].id,
    idUsuarioOrientadorFk: usuarios[10].id,
    cargaHoraria: 400,
    dataInicio: "2024-04-06",
    dataFim: "2024-06-08",
    status: "EM_FASE_INICIAL",
    nomeSupervisor: "Jéssica Cristina Carreira",
    emailSupervisor: "assizagaviao@gmail.com",
    telefoneSupervisor: "(69) 9 9317-7667",
    aditivo: false,
    tipoAditivo: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    idEmpresaFk: empresas[1].id,
    idEstagiarioFk: estagiarios[4].id,
    idUsuarioOrientadorFk: usuarios[5].id,
    cargaHoraria: 400,
    dataInicio: "2024-04-16",
    dataFim: "2024-04-22",
    status: "EM_FASE_INICIAL",
    nomeSupervisor: "Rafael Vieira",
    emailSupervisor: "rafael.vieira@ifro.edu.br",
    telefoneSupervisor: "(69) 99323-7730",
    aditivo: false,
    tipoAditivo: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// DISCIPLINAS
// ============================================
export const disciplinas = [
  {
    id: uuidv7(),
    nome: "Fundamentos de Programação",
    nomeAbreviado: "Fund. Prog",
    cargaHoraria: 60,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Banco de Dados",
    nomeAbreviado: "BD",
    cargaHoraria: 60,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Sistemas Operacionais",
    nomeAbreviado: "SO",
    cargaHoraria: 60,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Química Geral",
    nomeAbreviado: "Quím. Geral",
    cargaHoraria: 80,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Química Orgânica",
    nomeAbreviado: "Quím. Org",
    cargaHoraria: 80,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Ecologia Florestal",
    nomeAbreviado: "Ecol. Flor",
    cargaHoraria: 60,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Gestão Ambiental",
    nomeAbreviado: "Gest. Amb",
    cargaHoraria: 60,
    idImagemCapaFk: null,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];

// ============================================
// RESPONSÁVEIS DE EMPRESA
// ============================================
export const responsaveisEmpresa = [
  {
    id: uuidv7(),
    nome: "Jefferson Antônio dos Santos",
    cargo: "Diretor Técnico",
    email: "jefferson.santos@ifro.edu.br",
    telefone: "(69) 98226-0959",
    idEmpresaFk: empresas[0].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Isaura Isabel Conte",
    cargo: "Supervisora de Estágio",
    email: "isaura.conte@unir.br",
    telefone: "(69) 98484-5323",
    idEmpresaFk: empresas[1].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Antonny José Rincones Gonzales",
    cargo: "Gerente",
    email: "antonnyrincones@gmail.com",
    telefone: "(69) 99301-3785",
    idEmpresaFk: empresas[2].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Julio Cezar Carneiro Andrade",
    cargo: "Coordenador",
    email: "julio.carneiro@afya.com.br",
    telefone: "(69) 99235-3853",
    idEmpresaFk: empresas[3].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
  {
    id: uuidv7(),
    nome: "Ramila Silva de Jesus Estevam",
    cargo: "Gerente de Operações",
    email: "ramila-sjestevam@outlook.com",
    telefone: "(69) 99245-2572",
    idEmpresaFk: empresas[4].id,
    dateCreated: now,
    dateUpdated: now,
    dateDeleted: null,
  },
];
