// Re-export all entities from their respective modules for backwards compatibility
// Import directly from entity files to avoid circular dependencies with adapters

export { PerfilEntity } from "@/modules/acesso/perfil/infrastructure/persistence/typeorm/perfil.entity";
export { UsuarioEntity } from "@/modules/acesso/usuario/infrastructure/persistence/typeorm/usuario.entity";
export { AmbienteEntity } from "@/modules/ambientes/ambiente/infrastructure/persistence/typeorm/ambiente.entity";
export { BlocoEntity } from "@/modules/ambientes/bloco/infrastructure/persistence/typeorm/bloco.entity";
export { CampusEntity } from "@/modules/ambientes/campus/infrastructure/persistence/typeorm/campus.entity";
export { ReservaEntity } from "@/modules/ambientes/reserva/infrastructure/persistence/typeorm/reserva.entity";
export { ArquivoEntity } from "@/modules/armazenamento/arquivo/infrastructure/persistence/typeorm/arquivo.entity";
export { ImagemEntity } from "@/modules/armazenamento/imagem/infrastructure/persistence/typeorm/imagem.entity";
export { ImagemArquivoEntity } from "@/modules/armazenamento/imagem-arquivo/infrastructure/persistence/typeorm/imagem-arquivo.entity";
export { CursoEntity } from "@/modules/ensino/curso/infrastructure/persistence/typeorm/curso.entity";
export { DiarioEntity } from "@/modules/ensino/diario/infrastructure/persistence/typeorm/diario.entity";
export { DiarioPreferenciaAgrupamentoEntity } from "@/modules/ensino/diario-preferencia-agrupamento/infrastructure/persistence/typeorm/diario-preferencia-agrupamento.entity";
export { DiarioProfessorEntity } from "@/modules/ensino/diario-professor/infrastructure/persistence/typeorm/diario-professor.entity";
export { DisciplinaEntity } from "@/modules/ensino/disciplina/infrastructure/persistence/typeorm/disciplina.entity";
export { DisponibilidadeEntity } from "@/modules/ensino/disponibilidade/infrastructure/persistence/typeorm/disponibilidade.entity";
export { EtapaEntity } from "@/modules/ensino/etapa/infrastructure/persistence/typeorm/etapa.entity";
export { ModalidadeEntity } from "@/modules/ensino/modalidade/infrastructure/persistence/typeorm/modalidade.entity";
export { NivelFormacaoEntity } from "@/modules/ensino/nivel-formacao/infrastructure/persistence/typeorm/nivel-formacao.entity";
export { OfertaFormacaoEntity } from "@/modules/ensino/oferta-formacao/infrastructure/persistence/typeorm/oferta-formacao.entity";
export { OfertaFormacaoNivelFormacaoEntity } from "@/modules/ensino/oferta-formacao-nivel-formacao/infrastructure/persistence/typeorm/oferta-formacao-nivel-formacao.entity";
export { ProfessorIndisponibilidadeEntity } from "@/modules/ensino/professor-indisponibilidade/infrastructure/persistence/typeorm/professor-indisponibilidade.entity";
export { TurmaEntity } from "@/modules/ensino/turma/infrastructure/persistence/typeorm/turma.entity";
export { TurmaDisponibilidadeEntity } from "@/modules/ensino/turma-disponibilidade/infrastructure/persistence/typeorm/turma-disponibilidade.entity";
export { AulaEntity } from "@/modules/horarios/aula/infrastructure/persistence/typeorm/aula.entity";
export { CalendarioLetivoEntity } from "@/modules/horarios/calendario-letivo/infrastructure/persistence/typeorm/calendario-letivo.entity";
export { DiaCalendarioEntity } from "@/modules/horarios/dia-calendario/infrastructure/persistence/typeorm/dia-calendario.entity";
export { EventoEntity } from "@/modules/horarios/evento/infrastructure/persistence/typeorm/evento.entity";
export { GradeHorarioOfertaFormacaoEntity } from "@/modules/horarios/grade-horario-oferta-formacao/infrastructure/persistence/typeorm/grade-horario-oferta-formacao.entity";
export { GradeHorarioOfertaFormacaoIntervaloDeTempoEntity } from "@/modules/horarios/grade-horario-oferta-formacao-intervalo-de-tempo/infrastructure/persistence/typeorm/grade-horario-oferta-formacao-intervalo-de-tempo.entity";
export { HorarioGeradoEntity } from "@/modules/horarios/horario-gerado/infrastructure/persistence/typeorm/horario-gerado.entity";
export { HorarioGeradoAulaEntity } from "@/modules/horarios/horario-gerado-aula/infrastructure/persistence/typeorm/horario-gerado-aula.entity";
export { IntervaloDeTempoEntity } from "@/modules/horarios/intervalo-de-tempo/infrastructure/persistence/typeorm/intervalo-de-tempo.entity";
export { CidadeEntity } from "@/modules/localidades/cidade/infrastructure/persistence/typeorm/cidade.entity";
export { EnderecoEntity } from "@/modules/localidades/endereco/infrastructure/persistence/typeorm/endereco.entity";
export { EstadoEntity } from "@/modules/localidades/estado/infrastructure/persistence/typeorm/estado.entity";
export { EmpresaTypeormEntity } from "@/modules/estagio/empresa/infrastructure/persistence/empresa.typeorm.entity";
