name: "prepare: generate"
description: "prepares the repo for a job by running the generate"

inputs:
  workspace-generate:
    description: "workspace project generate"
    required: false
    default: "false"

runs:
  using: "composite"

  steps:
    - name: "generate all"
      if: ${{ inputs.workspace-generate == 'true' }}
      shell: bash
      run: bunx nx run @ladesa-ro/api.root:generate:all
