#!/usr/bin/env bash
set -euo pipefail

# Revert last database migration
exec bun x --bun typeorm -d lib/v2/adapters/out/persistence/typeorm/typeorm/data-sources/migration.data-source.ts migration:revert "$@"
