#!/usr/bin/env bash
set -euo pipefail

# Run database migrations
exec bun x --bun typeorm -d lib/modules/@shared/infrastructure/persistence/typeorm/data-sources/migration.data-source.ts migration:run "$@"
