export const EnvKeys = {
  // Database
  DB_SCHEMA: "DB_SCHEMA",
  DATABASE_URL: "DATABASE_URL",
  DATABASE_USE_SSL: "DATABASE_USE_SSL",

  // Runtime
  NODE_ENV: "NODE_ENV",
  PORT: "PORT",
  API_PREFIX: "API_PREFIX",
  BUILD_TIME: "BUILD_TIME",
  GIT_COMMIT_HASH: "GIT_COMMIT_HASH",
  SWAGGER_SERVERS: "SWAGGER_SERVERS",
  STORAGE_PATH: "STORAGE_PATH",
  LADESA_API_VERSION: "LADESA_API_VERSION",

  // Auth - OIDC
  OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER: "OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER",
  OAUTH2_CLIENT_REGISTRATION_LOGIN_CLIENT_ID: "OAUTH2_CLIENT_REGISTRATION_LOGIN_CLIENT_ID",
  OAUTH2_CLIENT_REGISTRATION_LOGIN_CLIENT_SECRET: "OAUTH2_CLIENT_REGISTRATION_LOGIN_CLIENT_SECRET",

  // Auth - Keycloak
  KC_BASE_URL: "KC_BASE_URL",
  KC_REALM: "KC_REALM",
  KC_CLIENT_ID: "KC_CLIENT_ID",
  KC_CLIENT_SECRET: "KC_CLIENT_SECRET",

  // Message Broker
  MESSAGE_BROKER_URL: "MESSAGE_BROKER_URL",
  MESSAGE_BROKER_QUEUE_TIMETABLE_REQUEST: "MESSAGE_BROKER_QUEUE_TIMETABLE_REQUEST",
  MESSAGE_BROKER_QUEUE_TIMETABLE_RESPONSE: "MESSAGE_BROKER_QUEUE_TIMETABLE_RESPONSE",
} as const;
