export const EnvKeys = {
  // Database
  DB_SCHEMA: "DB_SCHEMA",
  DATABASE_URL: "DATABASE_URL",
  DATABASE_USE_SSL: "DATABASE_USE_SSL",

  // Runtime
  NODE_ENV: "NODE_ENV",
  PORT: "PORT",
  API_PREFIX: "API_PREFIX",
  BUILD_TIME: "BUILD_TIME",
  GIT_COMMIT_HASH: "GIT_COMMIT_HASH",
  SWAGGER_SERVERS: "SWAGGER_SERVERS",
  STORAGE_PATH: "STORAGE_PATH",
  LADESA_API_VERSION: "LADESA_API_VERSION",
  ENABLE_MOCK_ACCESS_TOKEN: "ENABLE_MOCK_ACCESS_TOKEN",
  APP_PUBLIC_BASE_URL: "APP_PUBLIC_BASE_URL",

  // Auth - OIDC
  OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER: "OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER",
  OAUTH2_CLIENT_REGISTRATION_LOGIN_CLIENT_ID: "OAUTH2_CLIENT_REGISTRATION_LOGIN_CLIENT_ID",
  OAUTH2_CLIENT_REGISTRATION_LOGIN_CLIENT_SECRET: "OAUTH2_CLIENT_REGISTRATION_LOGIN_CLIENT_SECRET",

  // Auth - Keycloak
  KC_BASE_URL: "KC_BASE_URL",
  KC_REALM: "KC_REALM",
  KC_CLIENT_ID: "KC_CLIENT_ID",
  KC_CLIENT_SECRET: "KC_CLIENT_SECRET",
  KC_PASSWORD_RESET_REDIRECT_URI: "KC_PASSWORD_RESET_REDIRECT_URI",

  // Message Broker
  QUEUE_DATABASE_URL: "QUEUE_DATABASE_URL",
  QUEUE_SCHEMA: "QUEUE_SCHEMA",
  QUEUE_TIMETABLE_GENERATE: "QUEUE_TIMETABLE_GENERATE",
  QUEUE_FOLHA_PONTO_WHATSAPP: "QUEUE_FOLHA_PONTO_WHATSAPP",

  // WAHA (WhatsApp HTTP API)
  WAHA_BASE_URL: "WAHA_BASE_URL",
  WAHA_API_KEY: "WAHA_API_KEY",
  WAHA_TIMEOUT: "WAHA_TIMEOUT",
  WAHA_SESSION: "WAHA_SESSION",
  WAHA_WEBHOOK_HMAC_KEY: "WAHA_WEBHOOK_HMAC_KEY",
} as const;
