apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
  namespace: ladesa
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: web-service
      port: 80
      targetPort: web-port