**/.git
**/.husky
**/.github

**/.vscode
**/.idea

**/node_modules

**/*.env
**/*.env*

**/volumes

Dockerfile
*.dockerignore

Makefile

# deprecated

**/.pnpm-store
packages/*/test
packages/*/dist
packages/*/.dist
