apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: ladesa
spec:
  rules:
    - host: dev.ladesa.com.br
      http:
        paths:
          - path: /api/v1
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  name: web-service
