name: "prepare: install dependencies"
description: "prepares the repo by installing dependencies"

inputs:
  working-directory:
    description: "Override the working directory to run the installation in"
    required: false
    default: "."

  # bun-version:
  #   description: "The bun version to setup"
  #   required: true
  #   default: "latest"

  install-bun:
    description: "bun.js: install"
    required: false
    default: "true"

  install-bun-dependencies:
    description: "bun.js: install all dependencies"
    required: false
    default: "true"

runs:
  using: "composite"

  steps:
    - name: "print github workflow reference"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: echo ${{ github.ref }}

    - name: nx cache
      id: nx-cache
      uses: actions/cache@v4
      with:
        path: .nx/cache
        key: nx-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          nx-${{ github.ref_name }}-
          nx-

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ".bun-version"

    - name: use cached node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-management-service-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          node-modules-

    - name: "install dependencies"
      if: ${{ inputs.install-bun == 'true' }} && ${{ inputs.install-bun-dependencies == 'true' }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: bun install --frozen-lockfile
      env:
        HUSKY: "0"

    - uses: nrwl/nx-set-shas@v4
      with:
        main-branch-name: "development"
