FROM node:22-bookworm-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends protobuf-compiler=3.21.* \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -g ts-proto@2.12.0

WORKDIR /workspace
ENTRYPOINT ["bash", "-c"]
