// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: core/constraint_kind.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ladesa.TimetableGenerator.v1.Protobuf {

  /// <summary>Holder for reflection information generated from core/constraint_kind.proto</summary>
  public static partial class ConstraintKindReflection {

    #region Descriptor
    /// <summary>File descriptor for core/constraint_kind.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConstraintKindReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chpjb3JlL2NvbnN0cmFpbnRfa2luZC5wcm90bxIibGFkZXNhLnRpbWV0YWJs",
            "ZV9nZW5lcmF0b3IudjEuY29yZSJXChJDb25zdHJhaW50S2luZExpc3QSQQoF",
            "a2luZHMYASADKA4yMi5sYWRlc2EudGltZXRhYmxlX2dlbmVyYXRvci52MS5j",
            "b3JlLkNvbnN0cmFpbnRLaW5kKsICCg5Db25zdHJhaW50S2luZBIeChpHcm91",
            "cE9uZVNjaGVkdWxlQXRTYW1lVGltZRAAEiAKHFRlYWNoZXJPbmVTY2hlZHVs",
            "ZUF0U2FtZVRpbWUQARIgChxEaWFyeUxpbWl0U2NoZWR1bGVzSW5PbmVXZWVr",
            "EAISFwoTRGlhcnlMaW1pdFJlbWFpbmluZxADEhAKDFRlYWNoZXJMdW5jaBAE",
            "Eg4KCkdyb3VwTHVuY2gQBRIaChZUZWFjaGVyTm9PcHBvc2l0ZVR1cm5zEAYS",
            "EgoOVGVhY2hlcjEySG91cnMQBxIfChtHcm91cE5vT3ZlcmxhcHBpbmdUaW1l",
            "U2xvdHMQCBIhCh1UZWFjaGVyTm9PdmVybGFwcGluZ1RpbWVTbG90cxAJEh0K",
            "GVJvb21PbmVTY2hlZHVsZUF0U2FtZVRpbWUQCkIoqgIlTGFkZXNhLlRpbWV0",
            "YWJsZUdlbmVyYXRvci52MS5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKind), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKindList), global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKindList.Parser, new[]{ "Kinds" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ConstraintKind {
    [pbr::OriginalName("GroupOneScheduleAtSameTime")] GroupOneScheduleAtSameTime = 0,
    [pbr::OriginalName("TeacherOneScheduleAtSameTime")] TeacherOneScheduleAtSameTime = 1,
    [pbr::OriginalName("DiaryLimitSchedulesInOneWeek")] DiaryLimitSchedulesInOneWeek = 2,
    [pbr::OriginalName("DiaryLimitRemaining")] DiaryLimitRemaining = 3,
    [pbr::OriginalName("TeacherLunch")] TeacherLunch = 4,
    [pbr::OriginalName("GroupLunch")] GroupLunch = 5,
    [pbr::OriginalName("TeacherNoOppositeTurns")] TeacherNoOppositeTurns = 6,
    [pbr::OriginalName("Teacher12Hours")] Teacher12Hours = 7,
    [pbr::OriginalName("GroupNoOverlappingTimeSlots")] GroupNoOverlappingTimeSlots = 8,
    [pbr::OriginalName("TeacherNoOverlappingTimeSlots")] TeacherNoOverlappingTimeSlots = 9,
    [pbr::OriginalName("RoomOneScheduleAtSameTime")] RoomOneScheduleAtSameTime = 10,
  }

  #endregion

  #region Messages
  public sealed partial class ConstraintKindList : pb::IMessage<ConstraintKindList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConstraintKindList> _parser = new pb::MessageParser<ConstraintKindList>(() => new ConstraintKindList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConstraintKindList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKindReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConstraintKindList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConstraintKindList(ConstraintKindList other) : this() {
      kinds_ = other.kinds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConstraintKindList Clone() {
      return new ConstraintKindList(this);
    }

    /// <summary>Field number for the "kinds" field.</summary>
    public const int KindsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKind> _repeated_kinds_codec
        = pb::FieldCodec.ForEnum(10, x => (int) x, x => (global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKind) x);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKind> kinds_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKind>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKind> Kinds {
      get { return kinds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConstraintKindList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConstraintKindList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!kinds_.Equals(other.kinds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= kinds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      kinds_.WriteTo(output, _repeated_kinds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      kinds_.WriteTo(ref output, _repeated_kinds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += kinds_.CalculateSize(_repeated_kinds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConstraintKindList other) {
      if (other == null) {
        return;
      }
      kinds_.Add(other.kinds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            kinds_.AddEntriesFrom(input, _repeated_kinds_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            kinds_.AddEntriesFrom(ref input, _repeated_kinds_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
