// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: core/generate_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ladesa.TimetableGenerator.v1.Protobuf {

  /// <summary>Holder for reflection information generated from core/generate_request.proto</summary>
  public static partial class GenerateRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for core/generate_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GenerateRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtjb3JlL2dlbmVyYXRlX3JlcXVlc3QucHJvdG8SImxhZGVzYS50aW1ldGFi",
            "bGVfZ2VuZXJhdG9yLnYxLmNvcmUaEGNvcmUvZGlhcnkucHJvdG8aEmNvcmUv",
            "dGVhY2hlci5wcm90bxoQY29yZS9ncm91cC5wcm90bxoZY29yZS90aW1ldGFi",
            "bGVfZ3JpZC5wcm90bxoUY29yZS90aW1lX3Nsb3QucHJvdG8aGmNvcmUvY29u",
            "c3RyYWludF9raW5kLnByb3RvGiJjb3JlL3RpbWV0YWJsZV9ncmlkX3NjaGVk",
            "dWxlLnByb3RvGhljb3JlL3NoaWZ0X3NldHRpbmdzLnByb3RvIroHCg9HZW5l",
            "cmF0ZVJlcXVlc3QSEgoKZGF0ZV9zdGFydBgBIAEoCRIQCghkYXRlX2VuZBgC",
            "IAEoCRI5CgZncm91cHMYAyADKAsyKS5sYWRlc2EudGltZXRhYmxlX2dlbmVy",
            "YXRvci52MS5jb3JlLkdyb3VwEj0KCHRlYWNoZXJzGAQgAygLMisubGFkZXNh",
            "LnRpbWV0YWJsZV9nZW5lcmF0b3IudjEuY29yZS5UZWFjaGVyEjkKBmRpYXJ5",
            "cxgFIAMoCzIpLmxhZGVzYS50aW1ldGFibGVfZ2VuZXJhdG9yLnYxLmNvcmUu",
            "RGlhcnkSQAoKdGltZV9zbG90cxgGIAMoCzIsLmxhZGVzYS50aW1ldGFibGVf",
            "Z2VuZXJhdG9yLnYxLmNvcmUuVGltZVNsb3QSVwoXcHJldmlvdXNfdGltZXRh",
            "YmxlX2dyaWQYByABKAsyMS5sYWRlc2EudGltZXRhYmxlX2dlbmVyYXRvci52",
            "MS5jb3JlLlRpbWV0YWJsZUdyaWRIAIgBARIsCiRib29zdF9zYW1lX2RheV9v",
            "Zl93ZWVrX2FuZF90aW1lX3Nsb3QYCCABKAUSIwobYm9vc3Rfc2FtZV9kYXlf",
            "b2Zfd2Vla19vbmx5GAkgASgFEiEKGWJvb3N0X3NhbWVfdGltZV9zbG90X29u",
            "bHkYCiABKAUSLgomYm9vc3RfbGVzc2VyX2Rpc3RhbmNlX2Zyb21fZGF5X29m",
            "X3dlZWsYCyABKAUSLAokYm9vc3RfbGVzc2VyX2Rpc3RhbmNlX2Zyb21fdGlt",
            "ZV9zbG90GAwgASgFElgKE2VuYWJsZWRfY29uc3RyYWludHMYDSABKAsyNi5s",
            "YWRlc2EudGltZXRhYmxlX2dlbmVyYXRvci52MS5jb3JlLkNvbnN0cmFpbnRL",
            "aW5kTGlzdEgBiAEBElIKD2ZpeGVkX3NjaGVkdWxlcxgOIAMoCzI5LmxhZGVz",
            "YS50aW1ldGFibGVfZ2VuZXJhdG9yLnYxLmNvcmUuVGltZXRhYmxlR3JpZFNj",
            "aGVkdWxlEhgKEG5vbl9zY2hvb2xfZGF0ZXMYDyADKAkSTgoOc2hpZnRfc2V0",
            "dGluZ3MYECABKAsyMS5sYWRlc2EudGltZXRhYmxlX2dlbmVyYXRvci52MS5j",
            "b3JlLlNoaWZ0U2V0dGluZ3NIAogBAUIaChhfcHJldmlvdXNfdGltZXRhYmxl",
            "X2dyaWRCFgoUX2VuYWJsZWRfY29uc3RyYWludHNCEQoPX3NoaWZ0X3NldHRp",
            "bmdzQiiqAiVMYWRlc2EuVGltZXRhYmxlR2VuZXJhdG9yLnYxLlByb3RvYnVm",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Ladesa.TimetableGenerator.v1.Protobuf.DiaryReflection.Descriptor, global::Ladesa.TimetableGenerator.v1.Protobuf.TeacherReflection.Descriptor, global::Ladesa.TimetableGenerator.v1.Protobuf.GroupReflection.Descriptor, global::Ladesa.TimetableGenerator.v1.Protobuf.TimetableGridReflection.Descriptor, global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlotReflection.Descriptor, global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKindReflection.Descriptor, global::Ladesa.TimetableGenerator.v1.Protobuf.TimetableGridScheduleReflection.Descriptor, global::Ladesa.TimetableGenerator.v1.Protobuf.ShiftSettingsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ladesa.TimetableGenerator.v1.Protobuf.GenerateRequest), global::Ladesa.TimetableGenerator.v1.Protobuf.GenerateRequest.Parser, new[]{ "DateStart", "DateEnd", "Groups", "Teachers", "Diarys", "TimeSlots", "PreviousTimetableGrid", "BoostSameDayOfWeekAndTimeSlot", "BoostSameDayOfWeekOnly", "BoostSameTimeSlotOnly", "BoostLesserDistanceFromDayOfWeek", "BoostLesserDistanceFromTimeSlot", "EnabledConstraints", "FixedSchedules", "NonSchoolDates", "ShiftSettings" }, new[]{ "PreviousTimetableGrid", "EnabledConstraints", "ShiftSettings" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GenerateRequest : pb::IMessage<GenerateRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GenerateRequest> _parser = new pb::MessageParser<GenerateRequest>(() => new GenerateRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GenerateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ladesa.TimetableGenerator.v1.Protobuf.GenerateRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateRequest(GenerateRequest other) : this() {
      dateStart_ = other.dateStart_;
      dateEnd_ = other.dateEnd_;
      groups_ = other.groups_.Clone();
      teachers_ = other.teachers_.Clone();
      diarys_ = other.diarys_.Clone();
      timeSlots_ = other.timeSlots_.Clone();
      previousTimetableGrid_ = other.previousTimetableGrid_ != null ? other.previousTimetableGrid_.Clone() : null;
      boostSameDayOfWeekAndTimeSlot_ = other.boostSameDayOfWeekAndTimeSlot_;
      boostSameDayOfWeekOnly_ = other.boostSameDayOfWeekOnly_;
      boostSameTimeSlotOnly_ = other.boostSameTimeSlotOnly_;
      boostLesserDistanceFromDayOfWeek_ = other.boostLesserDistanceFromDayOfWeek_;
      boostLesserDistanceFromTimeSlot_ = other.boostLesserDistanceFromTimeSlot_;
      enabledConstraints_ = other.enabledConstraints_ != null ? other.enabledConstraints_.Clone() : null;
      fixedSchedules_ = other.fixedSchedules_.Clone();
      nonSchoolDates_ = other.nonSchoolDates_.Clone();
      shiftSettings_ = other.shiftSettings_ != null ? other.shiftSettings_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateRequest Clone() {
      return new GenerateRequest(this);
    }

    /// <summary>Field number for the "date_start" field.</summary>
    public const int DateStartFieldNumber = 1;
    private string dateStart_ = "";
    /// <summary>
    /// date-time
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateStart {
      get { return dateStart_; }
      set {
        dateStart_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "date_end" field.</summary>
    public const int DateEndFieldNumber = 2;
    private string dateEnd_ = "";
    /// <summary>
    /// date-time
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateEnd {
      get { return dateEnd_; }
      set {
        dateEnd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "groups" field.</summary>
    public const int GroupsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.v1.Protobuf.Group> _repeated_groups_codec
        = pb::FieldCodec.ForMessage(26, global::Ladesa.TimetableGenerator.v1.Protobuf.Group.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.Group> groups_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.Group>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.Group> Groups {
      get { return groups_; }
    }

    /// <summary>Field number for the "teachers" field.</summary>
    public const int TeachersFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.v1.Protobuf.Teacher> _repeated_teachers_codec
        = pb::FieldCodec.ForMessage(34, global::Ladesa.TimetableGenerator.v1.Protobuf.Teacher.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.Teacher> teachers_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.Teacher>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.Teacher> Teachers {
      get { return teachers_; }
    }

    /// <summary>Field number for the "diarys" field.</summary>
    public const int DiarysFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.v1.Protobuf.Diary> _repeated_diarys_codec
        = pb::FieldCodec.ForMessage(42, global::Ladesa.TimetableGenerator.v1.Protobuf.Diary.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.Diary> diarys_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.Diary>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.Diary> Diarys {
      get { return diarys_; }
    }

    /// <summary>Field number for the "time_slots" field.</summary>
    public const int TimeSlotsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot> _repeated_timeSlots_codec
        = pb::FieldCodec.ForMessage(50, global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot> timeSlots_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot> TimeSlots {
      get { return timeSlots_; }
    }

    /// <summary>Field number for the "previous_timetable_grid" field.</summary>
    public const int PreviousTimetableGridFieldNumber = 7;
    private global::Ladesa.TimetableGenerator.v1.Protobuf.TimetableGrid previousTimetableGrid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.v1.Protobuf.TimetableGrid PreviousTimetableGrid {
      get { return previousTimetableGrid_; }
      set {
        previousTimetableGrid_ = value;
      }
    }

    /// <summary>Field number for the "boost_same_day_of_week_and_time_slot" field.</summary>
    public const int BoostSameDayOfWeekAndTimeSlotFieldNumber = 8;
    private int boostSameDayOfWeekAndTimeSlot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BoostSameDayOfWeekAndTimeSlot {
      get { return boostSameDayOfWeekAndTimeSlot_; }
      set {
        boostSameDayOfWeekAndTimeSlot_ = value;
      }
    }

    /// <summary>Field number for the "boost_same_day_of_week_only" field.</summary>
    public const int BoostSameDayOfWeekOnlyFieldNumber = 9;
    private int boostSameDayOfWeekOnly_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BoostSameDayOfWeekOnly {
      get { return boostSameDayOfWeekOnly_; }
      set {
        boostSameDayOfWeekOnly_ = value;
      }
    }

    /// <summary>Field number for the "boost_same_time_slot_only" field.</summary>
    public const int BoostSameTimeSlotOnlyFieldNumber = 10;
    private int boostSameTimeSlotOnly_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BoostSameTimeSlotOnly {
      get { return boostSameTimeSlotOnly_; }
      set {
        boostSameTimeSlotOnly_ = value;
      }
    }

    /// <summary>Field number for the "boost_lesser_distance_from_day_of_week" field.</summary>
    public const int BoostLesserDistanceFromDayOfWeekFieldNumber = 11;
    private int boostLesserDistanceFromDayOfWeek_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BoostLesserDistanceFromDayOfWeek {
      get { return boostLesserDistanceFromDayOfWeek_; }
      set {
        boostLesserDistanceFromDayOfWeek_ = value;
      }
    }

    /// <summary>Field number for the "boost_lesser_distance_from_time_slot" field.</summary>
    public const int BoostLesserDistanceFromTimeSlotFieldNumber = 12;
    private int boostLesserDistanceFromTimeSlot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BoostLesserDistanceFromTimeSlot {
      get { return boostLesserDistanceFromTimeSlot_; }
      set {
        boostLesserDistanceFromTimeSlot_ = value;
      }
    }

    /// <summary>Field number for the "enabled_constraints" field.</summary>
    public const int EnabledConstraintsFieldNumber = 13;
    private global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKindList enabledConstraints_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKindList EnabledConstraints {
      get { return enabledConstraints_; }
      set {
        enabledConstraints_ = value;
      }
    }

    /// <summary>Field number for the "fixed_schedules" field.</summary>
    public const int FixedSchedulesFieldNumber = 14;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.v1.Protobuf.TimetableGridSchedule> _repeated_fixedSchedules_codec
        = pb::FieldCodec.ForMessage(114, global::Ladesa.TimetableGenerator.v1.Protobuf.TimetableGridSchedule.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.TimetableGridSchedule> fixedSchedules_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.TimetableGridSchedule>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Protobuf.TimetableGridSchedule> FixedSchedules {
      get { return fixedSchedules_; }
    }

    /// <summary>Field number for the "non_school_dates" field.</summary>
    public const int NonSchoolDatesFieldNumber = 15;
    private static readonly pb::FieldCodec<string> _repeated_nonSchoolDates_codec
        = pb::FieldCodec.ForString(122);
    private readonly pbc::RepeatedField<string> nonSchoolDates_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> NonSchoolDates {
      get { return nonSchoolDates_; }
    }

    /// <summary>Field number for the "shift_settings" field.</summary>
    public const int ShiftSettingsFieldNumber = 16;
    private global::Ladesa.TimetableGenerator.v1.Protobuf.ShiftSettings shiftSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.v1.Protobuf.ShiftSettings ShiftSettings {
      get { return shiftSettings_; }
      set {
        shiftSettings_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GenerateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GenerateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DateStart != other.DateStart) return false;
      if (DateEnd != other.DateEnd) return false;
      if(!groups_.Equals(other.groups_)) return false;
      if(!teachers_.Equals(other.teachers_)) return false;
      if(!diarys_.Equals(other.diarys_)) return false;
      if(!timeSlots_.Equals(other.timeSlots_)) return false;
      if (!object.Equals(PreviousTimetableGrid, other.PreviousTimetableGrid)) return false;
      if (BoostSameDayOfWeekAndTimeSlot != other.BoostSameDayOfWeekAndTimeSlot) return false;
      if (BoostSameDayOfWeekOnly != other.BoostSameDayOfWeekOnly) return false;
      if (BoostSameTimeSlotOnly != other.BoostSameTimeSlotOnly) return false;
      if (BoostLesserDistanceFromDayOfWeek != other.BoostLesserDistanceFromDayOfWeek) return false;
      if (BoostLesserDistanceFromTimeSlot != other.BoostLesserDistanceFromTimeSlot) return false;
      if (!object.Equals(EnabledConstraints, other.EnabledConstraints)) return false;
      if(!fixedSchedules_.Equals(other.fixedSchedules_)) return false;
      if(!nonSchoolDates_.Equals(other.nonSchoolDates_)) return false;
      if (!object.Equals(ShiftSettings, other.ShiftSettings)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DateStart.Length != 0) hash ^= DateStart.GetHashCode();
      if (DateEnd.Length != 0) hash ^= DateEnd.GetHashCode();
      hash ^= groups_.GetHashCode();
      hash ^= teachers_.GetHashCode();
      hash ^= diarys_.GetHashCode();
      hash ^= timeSlots_.GetHashCode();
      if (previousTimetableGrid_ != null) hash ^= PreviousTimetableGrid.GetHashCode();
      if (BoostSameDayOfWeekAndTimeSlot != 0) hash ^= BoostSameDayOfWeekAndTimeSlot.GetHashCode();
      if (BoostSameDayOfWeekOnly != 0) hash ^= BoostSameDayOfWeekOnly.GetHashCode();
      if (BoostSameTimeSlotOnly != 0) hash ^= BoostSameTimeSlotOnly.GetHashCode();
      if (BoostLesserDistanceFromDayOfWeek != 0) hash ^= BoostLesserDistanceFromDayOfWeek.GetHashCode();
      if (BoostLesserDistanceFromTimeSlot != 0) hash ^= BoostLesserDistanceFromTimeSlot.GetHashCode();
      if (enabledConstraints_ != null) hash ^= EnabledConstraints.GetHashCode();
      hash ^= fixedSchedules_.GetHashCode();
      hash ^= nonSchoolDates_.GetHashCode();
      if (shiftSettings_ != null) hash ^= ShiftSettings.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DateStart.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DateStart);
      }
      if (DateEnd.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DateEnd);
      }
      groups_.WriteTo(output, _repeated_groups_codec);
      teachers_.WriteTo(output, _repeated_teachers_codec);
      diarys_.WriteTo(output, _repeated_diarys_codec);
      timeSlots_.WriteTo(output, _repeated_timeSlots_codec);
      if (previousTimetableGrid_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(PreviousTimetableGrid);
      }
      if (BoostSameDayOfWeekAndTimeSlot != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(BoostSameDayOfWeekAndTimeSlot);
      }
      if (BoostSameDayOfWeekOnly != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(BoostSameDayOfWeekOnly);
      }
      if (BoostSameTimeSlotOnly != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(BoostSameTimeSlotOnly);
      }
      if (BoostLesserDistanceFromDayOfWeek != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(BoostLesserDistanceFromDayOfWeek);
      }
      if (BoostLesserDistanceFromTimeSlot != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(BoostLesserDistanceFromTimeSlot);
      }
      if (enabledConstraints_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(EnabledConstraints);
      }
      fixedSchedules_.WriteTo(output, _repeated_fixedSchedules_codec);
      nonSchoolDates_.WriteTo(output, _repeated_nonSchoolDates_codec);
      if (shiftSettings_ != null) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(ShiftSettings);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DateStart.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DateStart);
      }
      if (DateEnd.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DateEnd);
      }
      groups_.WriteTo(ref output, _repeated_groups_codec);
      teachers_.WriteTo(ref output, _repeated_teachers_codec);
      diarys_.WriteTo(ref output, _repeated_diarys_codec);
      timeSlots_.WriteTo(ref output, _repeated_timeSlots_codec);
      if (previousTimetableGrid_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(PreviousTimetableGrid);
      }
      if (BoostSameDayOfWeekAndTimeSlot != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(BoostSameDayOfWeekAndTimeSlot);
      }
      if (BoostSameDayOfWeekOnly != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(BoostSameDayOfWeekOnly);
      }
      if (BoostSameTimeSlotOnly != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(BoostSameTimeSlotOnly);
      }
      if (BoostLesserDistanceFromDayOfWeek != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(BoostLesserDistanceFromDayOfWeek);
      }
      if (BoostLesserDistanceFromTimeSlot != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(BoostLesserDistanceFromTimeSlot);
      }
      if (enabledConstraints_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(EnabledConstraints);
      }
      fixedSchedules_.WriteTo(ref output, _repeated_fixedSchedules_codec);
      nonSchoolDates_.WriteTo(ref output, _repeated_nonSchoolDates_codec);
      if (shiftSettings_ != null) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(ShiftSettings);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DateStart.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DateStart);
      }
      if (DateEnd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DateEnd);
      }
      size += groups_.CalculateSize(_repeated_groups_codec);
      size += teachers_.CalculateSize(_repeated_teachers_codec);
      size += diarys_.CalculateSize(_repeated_diarys_codec);
      size += timeSlots_.CalculateSize(_repeated_timeSlots_codec);
      if (previousTimetableGrid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PreviousTimetableGrid);
      }
      if (BoostSameDayOfWeekAndTimeSlot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoostSameDayOfWeekAndTimeSlot);
      }
      if (BoostSameDayOfWeekOnly != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoostSameDayOfWeekOnly);
      }
      if (BoostSameTimeSlotOnly != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoostSameTimeSlotOnly);
      }
      if (BoostLesserDistanceFromDayOfWeek != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoostLesserDistanceFromDayOfWeek);
      }
      if (BoostLesserDistanceFromTimeSlot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoostLesserDistanceFromTimeSlot);
      }
      if (enabledConstraints_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EnabledConstraints);
      }
      size += fixedSchedules_.CalculateSize(_repeated_fixedSchedules_codec);
      size += nonSchoolDates_.CalculateSize(_repeated_nonSchoolDates_codec);
      if (shiftSettings_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ShiftSettings);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GenerateRequest other) {
      if (other == null) {
        return;
      }
      if (other.DateStart.Length != 0) {
        DateStart = other.DateStart;
      }
      if (other.DateEnd.Length != 0) {
        DateEnd = other.DateEnd;
      }
      groups_.Add(other.groups_);
      teachers_.Add(other.teachers_);
      diarys_.Add(other.diarys_);
      timeSlots_.Add(other.timeSlots_);
      if (other.previousTimetableGrid_ != null) {
        if (previousTimetableGrid_ == null) {
          PreviousTimetableGrid = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimetableGrid();
        }
        PreviousTimetableGrid.MergeFrom(other.PreviousTimetableGrid);
      }
      if (other.BoostSameDayOfWeekAndTimeSlot != 0) {
        BoostSameDayOfWeekAndTimeSlot = other.BoostSameDayOfWeekAndTimeSlot;
      }
      if (other.BoostSameDayOfWeekOnly != 0) {
        BoostSameDayOfWeekOnly = other.BoostSameDayOfWeekOnly;
      }
      if (other.BoostSameTimeSlotOnly != 0) {
        BoostSameTimeSlotOnly = other.BoostSameTimeSlotOnly;
      }
      if (other.BoostLesserDistanceFromDayOfWeek != 0) {
        BoostLesserDistanceFromDayOfWeek = other.BoostLesserDistanceFromDayOfWeek;
      }
      if (other.BoostLesserDistanceFromTimeSlot != 0) {
        BoostLesserDistanceFromTimeSlot = other.BoostLesserDistanceFromTimeSlot;
      }
      if (other.enabledConstraints_ != null) {
        if (enabledConstraints_ == null) {
          EnabledConstraints = new global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKindList();
        }
        EnabledConstraints.MergeFrom(other.EnabledConstraints);
      }
      fixedSchedules_.Add(other.fixedSchedules_);
      nonSchoolDates_.Add(other.nonSchoolDates_);
      if (other.shiftSettings_ != null) {
        if (shiftSettings_ == null) {
          ShiftSettings = new global::Ladesa.TimetableGenerator.v1.Protobuf.ShiftSettings();
        }
        ShiftSettings.MergeFrom(other.ShiftSettings);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DateStart = input.ReadString();
            break;
          }
          case 18: {
            DateEnd = input.ReadString();
            break;
          }
          case 26: {
            groups_.AddEntriesFrom(input, _repeated_groups_codec);
            break;
          }
          case 34: {
            teachers_.AddEntriesFrom(input, _repeated_teachers_codec);
            break;
          }
          case 42: {
            diarys_.AddEntriesFrom(input, _repeated_diarys_codec);
            break;
          }
          case 50: {
            timeSlots_.AddEntriesFrom(input, _repeated_timeSlots_codec);
            break;
          }
          case 58: {
            if (previousTimetableGrid_ == null) {
              PreviousTimetableGrid = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimetableGrid();
            }
            input.ReadMessage(PreviousTimetableGrid);
            break;
          }
          case 64: {
            BoostSameDayOfWeekAndTimeSlot = input.ReadInt32();
            break;
          }
          case 72: {
            BoostSameDayOfWeekOnly = input.ReadInt32();
            break;
          }
          case 80: {
            BoostSameTimeSlotOnly = input.ReadInt32();
            break;
          }
          case 88: {
            BoostLesserDistanceFromDayOfWeek = input.ReadInt32();
            break;
          }
          case 96: {
            BoostLesserDistanceFromTimeSlot = input.ReadInt32();
            break;
          }
          case 106: {
            if (enabledConstraints_ == null) {
              EnabledConstraints = new global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKindList();
            }
            input.ReadMessage(EnabledConstraints);
            break;
          }
          case 114: {
            fixedSchedules_.AddEntriesFrom(input, _repeated_fixedSchedules_codec);
            break;
          }
          case 122: {
            nonSchoolDates_.AddEntriesFrom(input, _repeated_nonSchoolDates_codec);
            break;
          }
          case 130: {
            if (shiftSettings_ == null) {
              ShiftSettings = new global::Ladesa.TimetableGenerator.v1.Protobuf.ShiftSettings();
            }
            input.ReadMessage(ShiftSettings);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DateStart = input.ReadString();
            break;
          }
          case 18: {
            DateEnd = input.ReadString();
            break;
          }
          case 26: {
            groups_.AddEntriesFrom(ref input, _repeated_groups_codec);
            break;
          }
          case 34: {
            teachers_.AddEntriesFrom(ref input, _repeated_teachers_codec);
            break;
          }
          case 42: {
            diarys_.AddEntriesFrom(ref input, _repeated_diarys_codec);
            break;
          }
          case 50: {
            timeSlots_.AddEntriesFrom(ref input, _repeated_timeSlots_codec);
            break;
          }
          case 58: {
            if (previousTimetableGrid_ == null) {
              PreviousTimetableGrid = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimetableGrid();
            }
            input.ReadMessage(PreviousTimetableGrid);
            break;
          }
          case 64: {
            BoostSameDayOfWeekAndTimeSlot = input.ReadInt32();
            break;
          }
          case 72: {
            BoostSameDayOfWeekOnly = input.ReadInt32();
            break;
          }
          case 80: {
            BoostSameTimeSlotOnly = input.ReadInt32();
            break;
          }
          case 88: {
            BoostLesserDistanceFromDayOfWeek = input.ReadInt32();
            break;
          }
          case 96: {
            BoostLesserDistanceFromTimeSlot = input.ReadInt32();
            break;
          }
          case 106: {
            if (enabledConstraints_ == null) {
              EnabledConstraints = new global::Ladesa.TimetableGenerator.v1.Protobuf.ConstraintKindList();
            }
            input.ReadMessage(EnabledConstraints);
            break;
          }
          case 114: {
            fixedSchedules_.AddEntriesFrom(ref input, _repeated_fixedSchedules_codec);
            break;
          }
          case 122: {
            nonSchoolDates_.AddEntriesFrom(ref input, _repeated_nonSchoolDates_codec);
            break;
          }
          case 130: {
            if (shiftSettings_ == null) {
              ShiftSettings = new global::Ladesa.TimetableGenerator.v1.Protobuf.ShiftSettings();
            }
            input.ReadMessage(ShiftSettings);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
