// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: core/shift_settings.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ladesa.TimetableGenerator.v1.Protobuf {

  /// <summary>Holder for reflection information generated from core/shift_settings.proto</summary>
  public static partial class ShiftSettingsReflection {

    #region Descriptor
    /// <summary>File descriptor for core/shift_settings.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShiftSettingsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chljb3JlL3NoaWZ0X3NldHRpbmdzLnByb3RvEiJsYWRlc2EudGltZXRhYmxl",
            "X2dlbmVyYXRvci52MS5jb3JlGhRjb3JlL3RpbWVfc2xvdC5wcm90byLhAgoN",
            "U2hpZnRTZXR0aW5ncxI9Cgdtb3JuaW5nGAEgASgLMiwubGFkZXNhLnRpbWV0",
            "YWJsZV9nZW5lcmF0b3IudjEuY29yZS5UaW1lU2xvdBI/CglhZnRlcm5vb24Y",
            "AiABKAsyLC5sYWRlc2EudGltZXRhYmxlX2dlbmVyYXRvci52MS5jb3JlLlRp",
            "bWVTbG90EjsKBW5pZ2h0GAMgASgLMiwubGFkZXNhLnRpbWV0YWJsZV9nZW5l",
            "cmF0b3IudjEuY29yZS5UaW1lU2xvdBJJChNsdW5jaF9idWZmZXJfYmVmb3Jl",
            "GAQgASgLMiwubGFkZXNhLnRpbWV0YWJsZV9nZW5lcmF0b3IudjEuY29yZS5U",
            "aW1lU2xvdBJIChJsdW5jaF9idWZmZXJfYWZ0ZXIYBSABKAsyLC5sYWRlc2Eu",
            "dGltZXRhYmxlX2dlbmVyYXRvci52MS5jb3JlLlRpbWVTbG90QiiqAiVMYWRl",
            "c2EuVGltZXRhYmxlR2VuZXJhdG9yLnYxLlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlotReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ladesa.TimetableGenerator.v1.Protobuf.ShiftSettings), global::Ladesa.TimetableGenerator.v1.Protobuf.ShiftSettings.Parser, new[]{ "Morning", "Afternoon", "Night", "LunchBufferBefore", "LunchBufferAfter" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ShiftSettings : pb::IMessage<ShiftSettings>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ShiftSettings> _parser = new pb::MessageParser<ShiftSettings>(() => new ShiftSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ShiftSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ladesa.TimetableGenerator.v1.Protobuf.ShiftSettingsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShiftSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShiftSettings(ShiftSettings other) : this() {
      morning_ = other.morning_ != null ? other.morning_.Clone() : null;
      afternoon_ = other.afternoon_ != null ? other.afternoon_.Clone() : null;
      night_ = other.night_ != null ? other.night_.Clone() : null;
      lunchBufferBefore_ = other.lunchBufferBefore_ != null ? other.lunchBufferBefore_.Clone() : null;
      lunchBufferAfter_ = other.lunchBufferAfter_ != null ? other.lunchBufferAfter_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShiftSettings Clone() {
      return new ShiftSettings(this);
    }

    /// <summary>Field number for the "morning" field.</summary>
    public const int MorningFieldNumber = 1;
    private global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot morning_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot Morning {
      get { return morning_; }
      set {
        morning_ = value;
      }
    }

    /// <summary>Field number for the "afternoon" field.</summary>
    public const int AfternoonFieldNumber = 2;
    private global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot afternoon_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot Afternoon {
      get { return afternoon_; }
      set {
        afternoon_ = value;
      }
    }

    /// <summary>Field number for the "night" field.</summary>
    public const int NightFieldNumber = 3;
    private global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot night_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot Night {
      get { return night_; }
      set {
        night_ = value;
      }
    }

    /// <summary>Field number for the "lunch_buffer_before" field.</summary>
    public const int LunchBufferBeforeFieldNumber = 4;
    private global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot lunchBufferBefore_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot LunchBufferBefore {
      get { return lunchBufferBefore_; }
      set {
        lunchBufferBefore_ = value;
      }
    }

    /// <summary>Field number for the "lunch_buffer_after" field.</summary>
    public const int LunchBufferAfterFieldNumber = 5;
    private global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot lunchBufferAfter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot LunchBufferAfter {
      get { return lunchBufferAfter_; }
      set {
        lunchBufferAfter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ShiftSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ShiftSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Morning, other.Morning)) return false;
      if (!object.Equals(Afternoon, other.Afternoon)) return false;
      if (!object.Equals(Night, other.Night)) return false;
      if (!object.Equals(LunchBufferBefore, other.LunchBufferBefore)) return false;
      if (!object.Equals(LunchBufferAfter, other.LunchBufferAfter)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (morning_ != null) hash ^= Morning.GetHashCode();
      if (afternoon_ != null) hash ^= Afternoon.GetHashCode();
      if (night_ != null) hash ^= Night.GetHashCode();
      if (lunchBufferBefore_ != null) hash ^= LunchBufferBefore.GetHashCode();
      if (lunchBufferAfter_ != null) hash ^= LunchBufferAfter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (morning_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Morning);
      }
      if (afternoon_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Afternoon);
      }
      if (night_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Night);
      }
      if (lunchBufferBefore_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LunchBufferBefore);
      }
      if (lunchBufferAfter_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LunchBufferAfter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (morning_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Morning);
      }
      if (afternoon_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Afternoon);
      }
      if (night_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Night);
      }
      if (lunchBufferBefore_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LunchBufferBefore);
      }
      if (lunchBufferAfter_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LunchBufferAfter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (morning_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Morning);
      }
      if (afternoon_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Afternoon);
      }
      if (night_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Night);
      }
      if (lunchBufferBefore_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LunchBufferBefore);
      }
      if (lunchBufferAfter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LunchBufferAfter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ShiftSettings other) {
      if (other == null) {
        return;
      }
      if (other.morning_ != null) {
        if (morning_ == null) {
          Morning = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
        }
        Morning.MergeFrom(other.Morning);
      }
      if (other.afternoon_ != null) {
        if (afternoon_ == null) {
          Afternoon = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
        }
        Afternoon.MergeFrom(other.Afternoon);
      }
      if (other.night_ != null) {
        if (night_ == null) {
          Night = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
        }
        Night.MergeFrom(other.Night);
      }
      if (other.lunchBufferBefore_ != null) {
        if (lunchBufferBefore_ == null) {
          LunchBufferBefore = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
        }
        LunchBufferBefore.MergeFrom(other.LunchBufferBefore);
      }
      if (other.lunchBufferAfter_ != null) {
        if (lunchBufferAfter_ == null) {
          LunchBufferAfter = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
        }
        LunchBufferAfter.MergeFrom(other.LunchBufferAfter);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (morning_ == null) {
              Morning = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
            }
            input.ReadMessage(Morning);
            break;
          }
          case 18: {
            if (afternoon_ == null) {
              Afternoon = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
            }
            input.ReadMessage(Afternoon);
            break;
          }
          case 26: {
            if (night_ == null) {
              Night = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
            }
            input.ReadMessage(Night);
            break;
          }
          case 34: {
            if (lunchBufferBefore_ == null) {
              LunchBufferBefore = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
            }
            input.ReadMessage(LunchBufferBefore);
            break;
          }
          case 42: {
            if (lunchBufferAfter_ == null) {
              LunchBufferAfter = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
            }
            input.ReadMessage(LunchBufferAfter);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (morning_ == null) {
              Morning = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
            }
            input.ReadMessage(Morning);
            break;
          }
          case 18: {
            if (afternoon_ == null) {
              Afternoon = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
            }
            input.ReadMessage(Afternoon);
            break;
          }
          case 26: {
            if (night_ == null) {
              Night = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
            }
            input.ReadMessage(Night);
            break;
          }
          case 34: {
            if (lunchBufferBefore_ == null) {
              LunchBufferBefore = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
            }
            input.ReadMessage(LunchBufferBefore);
            break;
          }
          case 42: {
            if (lunchBufferAfter_ == null) {
              LunchBufferAfter = new global::Ladesa.TimetableGenerator.v1.Protobuf.TimeSlot();
            }
            input.ReadMessage(LunchBufferAfter);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
