ARG SDK_IMAGEM=mcr.microsoft.com/dotnet/sdk@sha256:35048e3a81e6a07c316e7bbbd80d80d2ba705fe5f23a8ed42b6638c8f4c20d30

FROM ${SDK_IMAGEM} AS restore

ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
    DOTNET_NOLOGO=1 \
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 \
    NUGET_XMLDOC_MODE=skip \
    DOTNET_gcServer=0 \
    DOTNET_EnableWriteXorExecute=0 \
    DOTNET_PROCESSOR_COUNT=2

WORKDIR /origem

COPY core/global.json ./
COPY core/domain/*.csproj core/domain/
COPY core/messages/*.csproj core/messages/
COPY core/application/*.csproj core/application/
COPY core/infrastructure.solver/*.csproj core/infrastructure.solver/
COPY core/test.solver/*.csproj core/test.solver/
COPY proto/generated-csharp/ proto/generated-csharp/

RUN dotnet restore core/test.solver/Ladesa.TimetableGenerator.Infrastructure.Solver.Test.csproj

FROM restore AS build

COPY core/ core/

RUN dotnet build core/infrastructure.solver/Ladesa.TimetableGenerator.Infrastructure.Solver.csproj \
      --configuration Release --no-restore -m:1 \
      -p:UseSharedCompilation=false

FROM build AS test

RUN dotnet test core/test.solver/Ladesa.TimetableGenerator.Infrastructure.Solver.Test.csproj \
      --configuration Release --no-restore -m:1 \
      -p:UseSharedCompilation=false \
      --logger "console;verbosity=normal"

FROM build AS publicar

ARG ALVO_RUNTIME=linux-x64

RUN dotnet publish core/presentation.console/Ladesa.TimetableGenerator.Console.csproj \
      --configuration Release --runtime ${ALVO_RUNTIME} --self-contained true \
      --output /publicado -m:1 -p:UseSharedCompilation=false
