ARG SDK_IMAGEM=mcr.microsoft.com/dotnet/sdk@sha256:35048e3a81e6a07c316e7bbbd80d80d2ba705fe5f23a8ed42b6638c8f4c20d30

FROM ${SDK_IMAGEM} AS restore

ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
    DOTNET_NOLOGO=1 \
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 \
    NUGET_XMLDOC_MODE=skip \
    DOTNET_gcServer=0 \
    DOTNET_EnableWriteXorExecute=0 \
    DOTNET_PROCESSOR_COUNT=2

WORKDIR /origem

COPY global.json ./
COPY domain/*.csproj domain/
COPY messages/*.csproj messages/
COPY application/*.csproj application/
COPY infrastructure.solver/*.csproj infrastructure.solver/
COPY test.solver/*.csproj test.solver/

RUN dotnet restore test.solver/Ladesa.TimetableGenerator.Infrastructure.Solver.Test.csproj

FROM restore AS build

COPY . .

RUN dotnet build infrastructure.solver/Ladesa.TimetableGenerator.Infrastructure.Solver.csproj \
      --configuration Release --no-restore -m:1 \
      -p:UseSharedCompilation=false

FROM build AS test

RUN dotnet test test.solver/Ladesa.TimetableGenerator.Infrastructure.Solver.Test.csproj \
      --configuration Release --no-restore -m:1 \
      -p:UseSharedCompilation=false \
      --logger "console;verbosity=normal"

FROM build AS publicar

ARG ALVO_RUNTIME=linux-x64

RUN dotnet publish presentation.console/Ladesa.TimetableGenerator.Console.csproj \
      --configuration Release --runtime ${ALVO_RUNTIME} --self-contained true \
      --output /publicado -m:1 -p:UseSharedCompilation=false
