apiVersion: v1
kind: Service
metadata:
  name: ladesa-ro-api
  labels:
    app: ladesa-ro-api
spec:
  type: NodePort
  selector:
    app: ladesa-ro-api
  ports:
    - name: web-service
      port: 80
      targetPort: web-port