#!/usr/bin/env bash
set -euo pipefail

# Run database migrations
exec bun x --bun typeorm -d lib/Ladesa.Management.Infrastructure.Database/typeorm/data-sources/migration.data-source.ts migration:run "$@"
