#!/usr/bin/env bash
set -euo pipefail

# TypeORM CLI with migration data source
exec ./.commands/typeorm -d lib/Ladesa.Management.Infrastructure.Database/typeorm/data-sources/migration.data-source.ts "$@"
