#!/usr/bin/env bash
set -euo pipefail

# TypeORM CLI with migration data source
exec ./.commands/typeorm -d lib/modules/@shared/infrastructure/persistence/typeorm/data-sources/migration.data-source.ts "$@"
