name: Restore Tasks Cache CI
description: ""

runs:
  using: "composite"
  steps:
    - name: Nx Cache
      id: nx-cache
      uses: actions/cache@v3
      with:
        path: .nx/cache
        key: nx-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          nx-${{ github.ref_name }}-
          nx-
