name: "[DEV] Build & Push"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-push.dev.yml
      - src/**/*
      - .docker/**/*

concurrency:
  group: build-deploy-dev

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASENAME: ${{ github.repository }}

jobs:
  ci:
    name: "CI: Build & Push"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: "[CI] Checkout do código-fonte"
        uses: actions/checkout@v7.0.1

      - name: "[CI] Set up QEMU"
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a

      - name: "[CI] Set up Docker Buildx"
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5

      - name: "[CI] Autenticação no GitHub Container Registry"
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: "[CI] Construção e publicação da imagem de contêiner"
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: ./src/
          file: .docker/Containerfile
          target: service-runtime
          push: true
          build-args: |
            BUILD_TIME=${{ github.event.head_commit.timestamp }}
            GIT_COMMIT_HASH=${{ github.sha }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/management-service:development
          cache-from: |
            type=gha,scope=management-service-dev
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/management-service:cache-development
          cache-to: |
            type=gha,scope=management-service-dev,mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/management-service:cache-development,mode=max

      - name: "[CI] Construção e publicação da imagem do timetable-worker"
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: ./src/infrastructure.timetable-generator/
          file: ./src/infrastructure.timetable-generator/worker/Containerfile
          target: runtime
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/timetable-worker:development
          cache-from: |
            type=gha,scope=timetable-worker-dev
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/timetable-worker:cache-development
          cache-to: |
            type=gha,scope=timetable-worker-dev,mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/timetable-worker:cache-development,mode=max
