name: "[DEV] Build & Push"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-push.dev.yml
      - src/**/*
      - .docker/**/*

concurrency:
  group: build-deploy-dev

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASENAME: ${{ github.repository }}

jobs:
  ci:
    name: "CI: Build & Push"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: "[CI] Checkout do código-fonte"
        uses: actions/checkout@v7.0.1

      - name: "[CI] Set up QEMU"
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8

      - name: "[CI] Set up Docker Buildx"
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c

      - name: "[CI] Autenticação no GitHub Container Registry"
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: "[CI] Construção e publicação da imagem de contêiner"
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: ./src/
          file: .docker/Containerfile
          target: service-runtime
          push: true
          build-args: |
            BUILD_TIME=${{ github.event.head_commit.timestamp }}
            GIT_COMMIT_HASH=${{ github.sha }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/management-service:development
          cache-from: |
            type=gha,scope=management-service-dev
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/management-service:cache-development
          cache-to: |
            type=gha,scope=management-service-dev,mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/management-service:cache-development,mode=max

      - name: "[CI] Construção e publicação da imagem do timetable-worker"
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: ./src/infrastructure.timetable-generator/
          file: ./src/infrastructure.timetable-generator/worker/Containerfile
          target: runtime
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/timetable-worker:development
          cache-from: |
            type=gha,scope=timetable-worker-dev
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/timetable-worker:cache-development
          cache-to: |
            type=gha,scope=timetable-worker-dev,mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/timetable-worker:cache-development,mode=max
