name: Continuos Deployment - API

on:
  workflow_dispatch:
  push:
    branches:
      - development

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  cd_build_push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    concurrency:
      group: cd-${{ github.ref }}-build
      cancel-in-progress: false

    steps:
      - name: determine infisical env-slug
        id: infisical-env-slug
        run: |
          if [[ $GITHUB_REF_NAME == 'production' ]]; then
            echo "env-slug=${{ secrets.INFISICAL_ENV_SLUG_PROD }}" >> "$GITHUB_ENV"
          else
            echo "env-slug=${{ secrets.INFISICAL_ENV_SLUG_DEV }}" >> "$GITHUB_ENV"
          fi

      - uses: Infisical/secrets-action@v1.0.7
        with:
          domain: ${{ secrets.INFISICAL_DOMAIN }}

          client-id: ${{ secrets.INFISICAL_MACHINE_IDENTITY_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET }}

          project-slug: ${{ secrets.INFISICAL_API_PROJECT_SLUG }}
          secret-path: ${{ secrets.INFISICAL_SECRET_API_PATH_BUILD_PUSH }}
          env-slug: dev

      - uses: ladesa-ro/esteira-ci-cd/actions/prepare-images-builder@main
        with:
          setup-qemu: "false"
          push-image: "true"

          push-image-registry-url: ${{ env.REGISTRY_URL }}
          push-image-registry-username: ${{ env.REGISTRY_USERNAME }}
          push-image-registry-token: ${{ env.REGISTRY_TOKEN }}

      - name: Build and push @ladesa-ro/api.service
        uses: ladesa-ro/esteira-ci-cd/actions/image-build-push@main
        with:
          image-tag: ${{ github.ref_name }}
          image-name: ${{ env.IMAGE_NAME  }}

          build-image: "true"
          build-target-tag: "api-service"

          push-image: "true"
          push-image-registry-url: ${{ env.REGISTRY_URL }}

  cd_deploy:
    if: 1 == 2
    name: Deploy to Cluster @ladesa-ro/api.service

    runs-on: deploy
    needs: [cd_build_push]

    environment:
      name: ${{ github.ref_name == 'development' && 'development' || 'production' }}
      url: ${{ env.DEPLOY_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: ladesa-ro/esteira-ci-cd/actions/deploy-k8s-stakater-application@main
        with:
          helm-values: ${{ env.DEPLOY_HELM_VALUES }}
          deployment: ${{ env.K8S_DEPLOYMENT }}
          namespace: ${{ env.K8S_NAMESPACE }}
          helm-release-name: ${{ env.K8S_DEPLOYMENT }}
          helm-release-extra-options: "--values=./api-service/examples/k8s/helm/values.common.yml"
