name: Continuos Deployment

on:
  push:
    branches:
      - production
      - development

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  cd_build_push_api:
    name: "Build and Push (api service)"
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build
      cancel-in-progress: false

    environment:
      name: ${{ github.ref_name == 'development' && 'development' || 'production' }}

    steps:
      - uses: ladesa-ro/esteira-ci-cd/actions/prepare-images-builder@main
        with:
          setup-qemu: "false"
          push-image: "true"
          push-image-registry-url: ${{ secrets.REGISTRY_URL }}
          push-image-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          push-image-registry-token: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push @ladesa-ro/api.service
        uses: ladesa-ro/esteira-ci-cd/actions/image-build-push@main
        with:
          image-tag: ${{ github.ref_name }}
          image-name: ${{ vars.IMAGE_NAME_SERVICE  }}

          build-image: "true"
          build-target-tag: "api-service"

          push-image: "true"
          push-image-registry-url: ${{ secrets.REGISTRY_URL }}

  cd_build_push_docs:
    name: "Build and Push - docs"
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build
      cancel-in-progress: false

    if: github.ref_name == 'development'

    environment:
      name: docs

    steps:
      - uses: ladesa-ro/esteira-ci-cd/actions/prepare-images-builder@main
        with:
          setup-qemu: "false"
          push-image: "true"
          push-image-registry-url: ${{ secrets.REGISTRY_URL }}
          push-image-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          push-image-registry-token: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push @ladesa-ro/api-client-fetch-docs
        uses: ladesa-ro/esteira-ci-cd/actions/image-build-push@main
        with:
          image-tag: ${{ github.ref_name }}
          image-name: ${{ vars.IMAGE_NAME_DOCS_NPM_API_CLIENT_FETCH  }}

          build-image: "true"
          build-target-tag: "npm-api-client-fetch-docs"

          push-image: "true"
          push-image-registry-url: ${{ secrets.REGISTRY_URL }}

  cd_deploy_api:
    name: Deploy to Cluster

    runs-on: deploy
    needs: [cd_build_push_api]

    environment:
      name: ${{ github.ref_name == 'development' && 'development' || 'production' }}
      url: ${{ vars.DEPLOY_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: ladesa-ro/esteira-ci-cd/actions/deploy-k8s-stakater-application@main
        with:
          helm-values: ${{ vars.DEPLOY_HELM_VALUES }}
          deployment: ${{ vars.K8S_DEPLOYMENT }}
          namespace: ${{ vars.K8S_NAMESPACE }}
          helm-release-name: ${{ vars.K8S_DEPLOYMENT }}
          helm-release-extra-options: "--values=./.devops/api-service/values.common.yml"
