name: Check Code Quality

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - development
  # push:
  #   branches:
  #     - development
  schedule:
    - cron: "0 9 * * 3"

concurrency:
  group: code-quality-${{ github.sha }}

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: aknowledge about origin/development
        run: git fetch -p origin development

      - name: it must install the dependencies
        uses: ./.github/actions/prepare/install
        with:
          install-bun: "true"

      - name: "generate:all should work"
        uses: ./.github/actions/prepare/generate
        with:
          workspace-generate: "true"

      - name: "build:all should work"
        uses: ./.github/actions/prepare/build
        with:
          workspace-build: "true"

      - name: require to pass static code check
        run: |
          git stash -u;

          bunx nx run @ladesa-ro/api.root:code-static:check;

          if [ `git stash list | wc -l` -gt 0 ]; then
            git stash pop;
          fi

      - name: require updated integrations
        run: |
          if [ `git status --porcelain=1 | wc -l` -ne 0 ]; then
            git status --porcelain=1;
            exit 1;
          fi

      - name: require changesets
        run: bunx changeset status --since=origin/development
